### ISSUE TITLE
Acceptance hiding in old coding area

### ISSUE THREAD

**Issue by loveshdongre** [loveshdongre/leetcode-enhancer#29]
Early, we had an issue were acceptance was not being hidden in coding area
ref: https://github.com/loveshdongre/leetcode-enhancer/issues/26

This PR was merged for hiding acceptance in new coding area:
https://github.com/loveshdongre/leetcode-enhancer/pull/28

However, for the old coding area (mode = 3), acceptance is not hidden.
This issue for hiding acceptance in the old coding area.

**Comment by natzelo** [comment]
Hi @loveshdongre ! 
I created another pull request
- #30

to add the hiding of acceptance rate in the old coding area. 
Let me know if you need me to make any changes. 

Also, my last commit didn't add me to the contributor's list. Probably because my `git config`  wasn't setup. Hopefully this merge should add me there as well. 

Anyways, love working with you and a project this useful

**Comment by loveshdongre** [comment]
hi @natzelo 
Thanks for the implementation of the old coding area as well. Would need some time for review and deployment.

It seemed strange to me as well when I didn't find you in the contributors' section.
As you mentioned `git config` wasn't set up, which was the issue in this case.

I've overwritten the history to update your email from `akshat@Akshats-MacBook-Air.local` to `akshat9300@gmail.com` and your name is now visible in the contributors list. [commit link](https://github.com/loveshdongre/leetcode-enhancer/commit/9bf17400c3f4832834cfac621952426b07210847.patch)

Would also be careful not to accept PRs without a proper email setup.
Thanks, I'm having a good experience working with you as well.
